Shop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from  django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/'  , include('accounts.urls')),
    path('products/' , include('products.urls')),
]
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import  (
ProductList,
ProductCreate,
ProductUpdate, 
ProductDelete
)



app_name='accounts'


urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),


    path("logout/", views.LogoutView.as_view(), name="logout"),
    # path(
    #     "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    # ),
    # path(
    #     "password_change/done/",
    #     views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    # path(
    #     "password_reset/done/",
    #     views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "reset/<uidb64>/<token>/",
    #     views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "reset/done/",
    #     views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
]


urlpatterns+=[
    path(''  , ProductList.as_view()  , name='home'),
    path('product/create/'  , ProductCreate.as_view()  , name='product_create'),
    path('product/update/<int:pk>/', ProductUpdate.as_view()  , name='product_update'),
    path('product/delete/<slug:slug>/'  , ProductDelete.as_view()  , name='product_delete'),


]

products/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from  django.conf.urls.static import static
from .views import home , ProductList , CategoryProductList , single_product , adminpage , ProductPreview

app_name = 'products'

urlpatterns = [

   path('' , home , name = 'home'),
   path('category/<slug:slug>/' , CategoryProductList.as_view() , name = 'category_page'),
   path('all/', ProductList.as_view() , name ='products'),
   path('preview/<int:pk>/', ProductPreview.as_view() , name ='preview'),
   path('single/<slug:slug>/' , single_product  , name = 'single_product'),
   path('admin/<slug:username>/' , adminpage , name ='admin')
   

]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import format_html
from accounts.models import User



class ProductManager(models.Manager):
    def published (self):

        return self.filter(status = 'p')


class CategoryManager(models.Manager):
    def published (self):
        return self.filter(status = True)


class Category(models.Model):
    title = models.CharField(max_length=100 , null=False , blank=False)
    slug = models.SlugField(max_length=50 , unique=True)
    image = models.ImageField(upload_to='categories' ,null=True , blank=True)
    status = models.BooleanField(default=True)
    parent = models.ForeignKey('self' , on_delete=models.CASCADE ,related_name='subcat' ,blank=True, null=True)








    class Meta :
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['status']


    def __str__(self):
        return self.title

    def get_thumbnail(self):
        return format_html(f"<img width='70' style='border-radius: 10px;' src='{self.image.url}'>")
    get_thumbnail.short_description = 'thumbnail'

    objects = CategoryManager()


class Product(models.Model):

    STATUS_CHOICES = (
        ('d' ,'draft'),
        ('p' , 'publish'),
        ('i','investigation'),
        ('b','backed'),

    )


    admin = models.ForeignKey(User , null=True , on_delete = models.SET_NULL , related_name='admin')
    title = models.CharField(max_length=50 , null=False , blank=False)
    slug = models.SlugField(max_length=50 , unique=True )
    description =models.TextField()
    categories = models.ManyToManyField('Category' , related_name='product' )
    price = models.BigIntegerField(null=True)
    image = models.ImageField(upload_to='products')
    created = models.DateTimeField(auto_now_add=True)
    #published = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1 , default='d' , choices=STATUS_CHOICES)
    stars = models.SmallIntegerField(default=0)


    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ['-created']

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse("accounts:home")

    def Rstars(self):
        return range(self.stars)

    def get_thumbnail(self):
        return format_html(f"<img width='70' style='border-radius: 10px;' src='{self.image.url}'>")
    get_thumbnail.short_description = 'thumbnail'

    def cat_to_str(self):
        return ' , '.join([cat.title for cat in self.categories.published()])

    cat_to_str.short_description = 'categories'








    objects = ProductManager()



# class User (models.Model):
#     name = models.CharField(max_length=50 , null=False , blank= False)
#     lastname = models.CharField(max_length=50 , null=False , blank=False)
#     username = models.CharField(max_length=50 , null=False , blank=False , unique=True)







products/views.py
from django.shortcuts import render , get_list_or_404 , get_object_or_404
from   .models import Product , Category
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic import ListView , DetailView
from accounts.models import User
from accounts.mixins import AdminAccessMixin



pcategories = Category.objects.filter(status=True , parent=None)

def home(request):

    cat = Category.objects.get(title='mens')
    product_men = cat.product.published()

    
    cat2 = Category.objects.get(title='womens')
    product_women = cat2.product.published()


    cat3 = Category.objects.get(title='kids')
    product_kids = cat3.product.published()



    
    context = {
        "categories": pcategories,
        "product_men":product_men[:4],
        "product_women":product_women[:4],
        "product_kids" : product_kids[:4],
        "cat_men" :cat,
        "cat_women" : cat2,
        "cat_kids" :cat3,
         }

    return render(request ,'products/index.html' , context=context)



# # def products(request):




#     products_list = Product.objects.filter(status='p')
#     paginator =Paginator(products_list , 6 )
#     page = request.GET.get('p')
#     products =paginator.get_page(page)
#     context = {
#         "products" :products,
#         "categories" :pcategories
#     }

#     return  render(request, 'products/products.html' , context=context)



class ProductList(ListView):
   
    paginate_by = 6
    queryset = Product.objects.published()
    template_name = 'products/products_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = pcategories
        return context
    









# def category(request , slug):

#     cat = Category.objects.get(slug = slug)
#     subcats = cat.subcat.filter(status = True)
#     product_list = cat.product.all()
#     paginator = Paginator(product_list , 6)
#     page = request.GET.get('p')
#     products = paginator.get_page(page)

#     context={
#         "products" : products,
#         "categories": pcategories,
#         "category":get_object_or_404(Category , status = True , slug=slug),
#         "subcats":subcats
#     }


#     return render(request , 'products/categories.html' , context= context)




class CategoryProductList(ListView):
    paginate_by = 6
    template_name = 'products/categories.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category , status = True , slug=slug)
        
        return category.product.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = pcategories
        context["category"] = category
        return context


class ProductPreview(AdminAccessMixin , DetailView):
    template_name = 'products/single-product.html'
    def get_object(self):
        global product
        pk = self.kwargs.get('pk')
        product = get_object_or_404(Product , pk=pk)

        return get_object_or_404(Product , pk=pk)


    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["admin"] = product.admin
        
        return context









        


    






def single_product(request , slug):
    product = get_object_or_404(Product , slug=slug , status='p')
    admin = product.admin
    print(admin)

    context = {
        "categories": pcategories,
        "admin" :admin,

        "product": product
    }

    return render(request , 'products/single-product.html' , context=context)












def adminpage(request , username):


    
    
    admin = User.objects.get(username = username)
    product_list = admin.admin.published()
    paginator = Paginator(product_list , 6)
    page = request.GET.get('p')
    products =paginator.get_page(page)
    context={
    "admin" : admin ,
    "categories": pcategories,
    "products" : products,

    }


    return render(request , 'products/admin_page.html' ,  context)

templates/products/admin_page.html
{% extends 'products/products.html' %}
{%  load static %}


{% block title %}{{admin.username}}{% endblock %}



{% block main-banner %}<h2>products from {{admin.username}}</h2>{%endblock%}



{% block header %}  
	<h2>Our Latest Products</h2>
	<span>Check out all of  products from {{admin.username}}.</span>

{% endblock %}



{% block products %}
<section class="section" id="products">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
            {% for product in products %}
                <div class="col-lg-4">
                    <div class="item">
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{% url 'products:single_product' product.slug %}"><i class="fa fa-eye"></i></a></li>
                                    <li><a href="single_product.html"><i class="fa fa-star"></i></a></li>
                                    <li><a href="single_product.html"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <a href="{% url 'products:single_product' product.slug %}"><img src="{{ product.image.url }}" alt=""></a>
                        </div>
                        <div class="down-content">
                            <h4>{{ product.title }}</h4>
                            <span>${{ product.price }}</span>
                            <ul class="stars">

                                {% for star in product.Rstars  %}
                                <li><i class="fa fa-star"></i></li>
                                {% endfor %}


                            </ul>
                        </div>
                    </div>
                </div>

                {% endfor %}
            <div class="col-lg-12">
                    <div class="pagination">
                        <ul>
                            {% if products.has_previous %}
                                <li class="active">
                                    <a href="{% url 'products:admin' admin.username %}?p={{ products.previous_page_number }}"><</a>
                                </li>
                            {% endif %}

                            {% if products.has_next %}
                                <li class="active">
                                    <a href="{% url 'products:admin' admin.username %}?p={{ products.next_page_number }}">></a>
                                </li>
                            {% endif %}

                            


                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Majid Shop | {% block title %}{% endblock %}</title>


    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'products/assets/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'products/assets/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'products/assets/css/templatemo-hexashop.css' %}">

    <link rel="stylesheet" href="{% static 'products/assets/css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'products/assets/css/lightbox.css' %}">
<!--

TemplateMo 571 Hexashop

https://templatemo.com/tm-571-hexashop

-->    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="{% static 'products/assets/images/logo.png' %}">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
    <ul class="nav">
                            <li class="scroll-to-section"><a class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'products:home' %}" >Home</a></li>
                            <li class="scroll-to-section"><a  class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}" href="{% url 'products:products' %}">Products</a></li>
                            <li class="submenu">
                                <a class="{% if request.resolver_match.url_name == 'category_page' %}active{% endif %}" href="javascript:;">Categories</a>
                                <ul>
                                    {% for cat in categories %}
                                        <li><a href="{% url 'products:category_page' cat.slug %}">{{ cat.title }}</a></li>
                                    {% endfor %}


                                </ul>
                            </li>

                            <li class="scroll-to-section"><a href="{% url 'accounts:home' %}">Manager</a></li>                           
                             <li class="scroll-to-section"><a href="index.html">About us</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    </head>

  {% block main %}

  {% endblock %}



    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="first-item">
                        <div class="logo">
                            <img src="{% static 'products/assets/images/white-logo.png' %}" alt="hexashop ecommerce templatemo">
                        </div>
                        <ul>
                            <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                            <li><a href="#">hexashop@company.com</a></li>
                            <li><a href="#">010-020-0340</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <h4>Shopping &amp; Categories</h4>
                    <ul>
                        <li><a href="#">Men’s Shopping</a></li>
                        <li><a href="#">Women’s Shopping</a></li>
                        <li><a href="#">Kid's Shopping</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Homepage</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Help &amp; Information</h4>
                    <ul>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">FAQ's</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Tracking ID</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">
                        <p>Copyright © 2022 HexaShop Co., Ltd. All Rights Reserved.
<!--                                 {{request.resolver_match}}
 -->                        <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


    </footer>
    <script src="{% static 'products/assets/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'products/assets/js/popper.js' %}"></script>
    <script src="{% static 'products/assets/js/bootstrap.min.js' %}"></script>

    <!-- Plugins -->
    <script src="{% static 'products/assets/js/owl-carousel.js' %}"></script>
    <script src="{% static 'products/assets/js/accordions.js' %}"></script>
    <script src="{% static 'products/assets/js/datepicker.js' %}"></script>
    <script src="{% static 'products/assets/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'products/assets/js/waypoints.min.js' %}"></script>
    <script src="{% static 'products/assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'products/assets/js/imgfix.min.js' %}"></script>
    <script src="{% static 'products/assets/js/slick.js' %}"></script>
    <script src="{% static 'products/assets/js/lightbox.js' %}"></script>
    <script src="{% static 'products/assets/js/isotope.js' %}"></script>

    <!-- Global Init -->
    <script src="{% static 'products/assets/js/custom.js' %}"></script>

    <script>

        $(function() {
            var selectedClass = "";
            $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
              $("."+selectedClass).fadeIn();
              $("#portfolio").fadeTo(50, 1);
            }, 500);

            });
        });

    </script>

  </body>
</html>

templates/products/categories.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}{{ category.title }}{% endblock %}
{% block main %}
                                
    <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->


    <!-- ***** Header Area Start ***** -->

    <!-- ***** Header Area End ***** -->

    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top">

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Check The Latest {{ category }}</h2>
                        <span>:)</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Products Area Starts ***** -->
    <section class="section" id="products">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">

                        <h2>Our Latest {{ category }}</h2>
                        <span>Check out all of our {{ category }}.</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
            {% for product in object_list %}
                <div class="col-lg-4">
                    <div class="item">
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{% url 'products:single_product' product.slug %}"><i class="fa fa-eye"></i></a></li>
                                    <li><a href="single_product.html"><i class="fa fa-star"></i></a></li>
                                    <li><a href="single_product.html"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <a href="{% url 'products:single_product' product.slug %}"><img src="{{ product.image.url }}" alt=""></a>

                        </div>
                        <div class="down-content">
                            <h4>{{ product.title }}</h4>
                            <span>${{ product.price }}</span>
                            <ul class="stars">

                                {% for star in product.Rstars  %}
                                <li><i class="fa fa-star"></i></li>
                                {% endfor %}


                            </ul>
                        </div>
                    </div>
                </div>

                {% endfor %}
            <div class="col-lg-12">
                    <div class="pagination">
                        <ul>


                            {% if page_obj.has_previous %}
                                <li class="active">
                                    <a href="{% url 'products:category_page' category.slug  %}?page={{ page_obj.previous_page_number }}" ><</a>
                                </li>
                            {% endif %}
                         {% if page_obj.has_next %}
                                <li class="active">
                                    <a href="{% url 'products:category_page' category.slug  %}?page={{ page_obj.next_page_number }}">></a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/products/products_list.html
{% extends 'products/products.html' %}
{%  load static %}

{% block title %}Products{% endblock %}

{% block main-banner %}<h2>Check The Latest products </h2>{%endblock%}

 {% block header %}
 
 <h2>Our Latest Products</h2>
<span>Check out all of our products.</span>

{% endblock %}

{% block products %}
<section class="section" id="products">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
            {% for product in object_list %}
                <div class="col-lg-4">
                    <div class="item">
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{% url 'products:single_product' product.slug %}"><i class="fa fa-eye"></i></a></li>
                                    <li><a href="single_product.html"><i class="fa fa-star"></i></a></li>
                                    <li><a href="single_product.html"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <a href="{% url 'products:single_product' product.slug %}"><img src="{{ product.image.url }}" alt=""></a>
                        </div>
                        <div class="down-content">
                            <h4>{{ product.title }}</h4>
                            <span>${{ product.price }}</span>
                            <ul class="stars">

                                {% for star in product.Rstars  %}
                                <li><i class="fa fa-star"></i></li>
                                {% endfor %}


                            </ul>
                        </div>
                    </div>
                </div>

                {% endfor %}
            <div class="col-lg-12">
                    <div class="pagination">
                        <ul>
                            {% if page_obj.has_previous %}
                                <li class="active">
                                    <a href="{% url 'products:products'  %}?page={{ page_obj.previous_page_number }}"><</a>
                                </li>
                            {% endif %}
                            {% if page_obj.has_next %}
                                <li class="active">
                                    <a href="{% url 'products:products'  %}?page={{ page_obj.next_page_number }}">></a>
                                </li>
                            {% endif %}


                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </section>
    {% endblock %}

templates/products/single-product.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}{{product.slug}}{% endblock %}

{% block main %}
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->

    <!-- ***** Header Area End ***** -->

    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>{{product.title}}</h2>
                        <span>{{product.slug}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Product Area Starts ***** -->
    <section class="section" id="product">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                <div class="left-images">
                    <img src="{{product.image.url}}" alt="">

                </div>
            </div>
            <div class="col-lg-4">
                <div class="right-content">
                    <h4>{{product.title}}</h4>
                    <span class="price">${{product.price}}</span>
                    <ul class="stars">
                        {% for s in product.Rstars %}
                        <li><i class="fa fa-star"></i></li>
                        {% endfor %}


                    </ul>

                    <div class="quote">
                        <i class="fa fa-quote-left"></i><p>{{product.description|safe}}</p>
                    </div>
                    <span>{{product.created}}</span>
                    <div class="quantity-content">
                        <div class="left-content">
                            <h6>No. of Orders</h6>
                        </div>
                        <div class="right-content">
                            <div class="quantity buttons_added">
                                <input type="button" value="-" class="minus"><input type="number" step="1" min="1" max="" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" pattern="" inputmode=""><input type="button" value="+" class="plus">
                            </div>
                        </div>
                    </div>
                    <div class="total">
                        <h4>Total: ${{product.price}}</h4>
                        <div class="main-border-button"><a href="#">Add To Cart</a></div>


                    </div>


                    <div>
                        <ul>
                            {% for cat in product.categories.published %}
                             
                             <a href="{% url 'products:category_page' cat.slug %}"><h5>#{{cat.title}}</h5></a>
                             
                                
                            {% endfor %}


                        </ul>

                    </div>
                </div>
                <br>
                <div>
                        <h4 >Added By <a href="{% url 'products:admin' admin.username %}">{{admin.username}}</a></h4 >

                        
                    </div>
            </div>
            </div>
        </div>
    </section>
    <!-- ***** Product Area Ends ***** -->
    
    <!-- ***** Footer Start ***** -->
 {% endblock %}